- name: instyall and run nginx server
  hosts: web
  become: yes
  tasks: 
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
  - name: Enable nginx
    ansible.builtin.service:
      name: nginx
      enabled: yes    